version: '3'
services:
  dns:
    image: jrcichra/lancachenet-lancache-dns:latest
    env_file: .env
    ports:
      - ${DNS_BIND_IP}:53:53/udp
  sniproxy:
    image: jrcichra/lancachenet-sniproxy:latest
    env_file: .env
    ports:
      - 443:443/tcp
  monolithic:
    image: jrcichra/lancachenet-monolithic:latest
    env_file: .env
    ports:
      - 80:80/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
