version: '2'
services:
  proxy:
    image: jrcichra/jwilder-nginx-proxy-armv7
    env_file: .env
    ports:
      - ${LANCACHE_IP}:80:80/tcp
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    env_file: .env
  dns:
    image: jrcichra/lancachenet-lancache-dns:latest
    env_file: .env
    ports:
      - ${DNS_IP}:53:53/udp
  sniproxy:
    image: jrcichra/lancachenet-sniproxy:latest
    env_file: .env
    ports:
      - 443:443/tcp
  arenanet:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/arenanet/cache:/data/cache
      - ${CACHE_ROOT}/arenanet/logs:/data/logs
    environment:
      - VIRTUAL_HOST=assetcdn.101.arenanetworks.com,assetcdn.102.arenanetworks.com,assetcdn.103.arenanetworks.com,live.patcher.bladeandsoul.com
    restart: always
  blizzard:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/blizzard/cache:/data/cache
      - ${CACHE_ROOT}/blizzard/logs:/data/logs
    environment:
      - VIRTUAL_HOST=dist.blizzard.com,dist.blizzard.com.edgesuite.net,llnw.blizzard.com,edgecast.blizzard.com,blizzard.vo.llnwd.net,blzddist1-a.akamaihd.net,blzddist2-a.akamaihd.net,blzddist3-a.akamaihd.net,blzddist4-a.akamaihd.net,level3.blizzard.com,nydus.battle.net,edge.blizzard.top.comcast.net,cdn.blizzard.com,*.cdn.blizzard.com
    restart: always
  cityofheroes:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/cityofheroes/cache:/data/cache
      - ${CACHE_ROOT}/cityofheroes/logs:/data/logs
    environment:
      - VIRTUAL_HOST=cdn.homecomingservers.com
    restart: always
  daybreak:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/daybreak/cache:/data/cache
      - ${CACHE_ROOT}/daybreak/logs:/data/logs
    environment:
      - VIRTUAL_HOST=pls.patch.daybreakgames.com
    restart: always
  epicgames:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/epicgames/cache:/data/cache
      - ${CACHE_ROOT}/epicgames/logs:/data/logs
    environment:
      - VIRTUAL_HOST=epicgames-download1.akamaized.net,download.epicgames.com,download2.epicgames.com,download3.epicgames.com,download4.epicgames.com
    restart: always
  frontier:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/frontier/cache:/data/cache
      - ${CACHE_ROOT}/frontier/logs:/data/logs
    environment:
      - VIRTUAL_HOST=cdn.zaonce.net
    restart: always
  hirez:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/hirez/cache:/data/cache
      - ${CACHE_ROOT}/hirez/logs:/data/logs
    environment:
      - VIRTUAL_HOST=hirez.http.internapcdn.net
    restart: always
  nexusmods:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/nexusmods/cache:/data/cache
      - ${CACHE_ROOT}/nexusmods/logs:/data/logs
    environment:
      - VIRTUAL_HOST=filedelivery.nexusmods.com
    restart: always
  neverwinter:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/neverwinter/cache:/data/cache
      - ${CACHE_ROOT}/neverwinter/logs:/data/logs
    environment:
      - VIRTUAL_HOST=level3.nwhttppatch.crypticstudios.com
    restart: always
  nintendo:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/nintendo/cache:/data/cache
      - ${CACHE_ROOT}/nintendo/logs:/data/logs
    environment:
      - VIRTUAL_HOST=ccs.cdn.wup.shop.nintendo.com,ccs.cdn.wup.shop.nintendo.net,ccs.cdn.wup.shop.nintendo.net.edgesuite.net,geisha-wup.cdn.nintendo.net,geisha-wup.cdn.nintendo.net.edgekey.net,idbe-wup.cdn.nintendo.net,idbe-wup.cdn.nintendo.net.edgekey.net,ecs-lp1.hac.shop.nintendo.net,receive-lp1.dg.srv.nintendo.net,*.wup.shop.nintendo.net,*.wup.eshop.nintendo.net,*.hac.lp1.d4c.nintendo.net,*.hac.lp1.eshop.nintendo.net
    restart: always
  renegadex:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/renegadex/cache:/data/cache
      - ${CACHE_ROOT}/renegadex/logs:/data/logs
    environment:
      - VIRTUAL_HOST=rxp-fl.cncirc.net,rxp-chi.cncirc.net,rxp-nz.cncirc.net,rxp-bgr.cncirc.net,rxp-fr.cncirc.net,rxp-nyc.cncirc.net,rxp-uk.cncirc.net,rxp-sg.cncirc.net,rxp-la.cncirc.net,rxp-fin.cncirc.net,denver1.renegade-x.com,seattle1.renegade-x.com
    restart: always
  riot:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/riot/cache:/data/cache
      - ${CACHE_ROOT}/riot/logs:/data/logs
    environment:
      - VIRTUAL_HOST=l3cdn.riotgames.com,worldwide.l3cdn.riotgames.com,riotgamespatcher-a.akamaihd.net,riotgamespatcher-a.akamaihd.net.edgesuite.net,*.dyn.riotcdn.net
    restart: always
  rockstar:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/rockstar/cache:/data/cache
      - ${CACHE_ROOT}/rockstar/logs:/data/logs
    environment:
      - VIRTUAL_HOST=patches.rockstargames.com
    restart: always
  sony:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/sony/cache:/data/cache
      - ${CACHE_ROOT}/sony/logs:/data/logs
    environment:
      - VIRTUAL_HOST=pls.patch.station.sony.com,gs2.ww.prod.dl.playstation.net,gs2.sonycoment.loris-e.llnwd.net
    restart: always
  steam:
    image: jrcichra/lancachenet-${STEAMCACHE_CONTAINER}:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/steam/cache:/data/cache
      - ${CACHE_ROOT}/steam/logs:/data/logs
    environment:
      - VIRTUAL_HOST=*.content.steampowered.com,content1.steampowered.com,content2.steampowered.com,content3.steampowered.com,content4.steampowered.com,content5.steampowered.com,content6.steampowered.com,content7.steampowered.com,content8.steampowered.com,cs.steampowered.com,steamcontent.com,client-download.steampowered.com,*.hsar.steampowered.com.edgesuite.net,*.akamai.steamstatic.com,content-origin.steampowered.com,clientconfig.akamai.steamtransparent.com,steampipe.akamaized.net,edgecast.steamstatic.com,steam.apac.qtlglb.com.mwcloudcdn.com,*.cs.steampowered.com,*.cm.steampowered.com,*.edgecast.steamstatic.com,*.steamcontent.com,cdn1-sea1.valve.net,cdn2-sea1.valve.net,*.steam-content-dnld-1.apac-1-cdn.cqloud.com,*.steam-content-dnld-1.eu-c1-cdn.cqloud.com,steam.apac.qtlglb.com,edge.steam-dns.top.comcast.net,edge.steam-dns-2.top.comcast.net,steam.naeu.qtlglb.com,steampipe-kr.akamaized.net,steam.ix.asn.au,steam.eca.qtlglb.com,steam.cdn.on.net,update5.dota2.wmsj.cn,update2.dota2.wmsj.cn,update6.dota2.wmsj.cn,update3.dota2.wmsj.cn,update1.dota2.wmsj.cn,update4.dota2.wmsj.cn,update5.csgo.wmsj.cn,update2.csgo.wmsj.cn,update4.csgo.wmsj.cn,update3.csgo.wmsj.cn,update6.csgo.wmsj.cn,update1.csgo.wmsj.cn,st.dl.bscstorage.net,cdn.mileweb.cs.steampowered.com.8686c.com
    restart: always
  uplay:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/uplay/cache:/data/cache
      - ${CACHE_ROOT}/uplay/logs:/data/logs
    environment:
      - VIRTUAL_HOST=*.cdn.ubi.com
    restart: always
  teso:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/teso/cache:/data/cache
      - ${CACHE_ROOT}/teso/logs:/data/logs
    environment:
      - VIRTUAL_HOST=live.patcher.elderscrollsonline.com
    restart: always
  twitch:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/twitch/cache:/data/cache
      - ${CACHE_ROOT}/twitch/logs:/data/logs
    environment:
      - VIRTUAL_HOST=d3rmjivj4k4f0t.cloudfront.net,addons.forgesvc.net,media.forgecdn.net,files.forgecdn.net
    restart: always
  warframe:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/warframe/cache:/data/cache
      - ${CACHE_ROOT}/warframe/logs:/data/logs
    environment:
      - VIRTUAL_HOST=content.warframe.com
    restart: always
  wargaming:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/wargaming/cache:/data/cache
      - ${CACHE_ROOT}/wargaming/logs:/data/logs
    environment:
      - VIRTUAL_HOST=dl1.wargaming.net,dl2.wargaming.net,wg.gcdn.co,wgusst-na.wargaming.net,wgusst-eu.wargaming.net,update-v4r4h10x.worldofwarships.com,wgus-wotasia.wargaming.net,dl-wot-ak.wargaming.net,dl-wot-gc.wargaming.net,dl-wot-se.wargaming.net,dl-wot-cdx.wargaming.net,dl-wows-ak.wargaming.net,dl-wows-gc.wargaming.net,dl-wows-se.wargaming.net,dl-wows-cdx.wargaming.net,dl-wowp-ak.wargaming.net,dl-wowp-gc.wargaming.net,dl-wowp-se.wargaming.net,dl-wowp-cdx.wargaming.net
    restart: always
  wsus:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/wsus/cache:/data/cache
      - ${CACHE_ROOT}/wsus/logs:/data/logs
    environment:
      - VIRTUAL_HOST=officecdn.microsoft.com,*.windowsupdate.com,windowsupdate.com,*.dl.delivery.mp.microsoft.com,dl.delivery.mp.microsoft.com,*.update.microsoft.com,*.do.dsp.mp.microsoft.com,*.microsoft.com.edgesuite.net,amupdatedl.microsoft.com,amupdatedl2.microsoft.com,amupdatedl3.microsoft.com,amupdatedl4.microsoft.com,amupdatedl5.microsoft.com
    restart: always
  xboxlive:
    image: jrcichra/lancachenet-generic:latest
    env_file: .env
    volumes:
      - ${CACHE_ROOT}/xboxlive/cache:/data/cache
      - ${CACHE_ROOT}/xboxlive/logs:/data/logs
    environment:
      - VIRTUAL_HOST=assets1.xboxlive.com,assets2.xboxlive.com,dlassets.xboxlive.com,xboxone.loris.llnwd.net,*.xboxone.loris.llnwd.net,xboxone.vo.llnwd.net,xbox-mbr.xboxlive.com,assets1.xboxlive.com.nsatc.net
    restart: always
