name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare environment for buildx
      run: bash -x prep.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push lancachenet/ubuntu
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        git clone https://github.com/lancachenet/ubuntu.git
        cd ubuntu
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t jrcichra/lancachenet-ubuntu --push .
        cd ..
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push lancachenet/ubuntu-nginx
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        git clone https://github.com/lancachenet/ubuntu-nginx.git
        cd ubuntu-nginx
        sed -i '1cFROM jrcichra/lancachenet-ubuntu' Dockerfile
        cat Dockerfile
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t jrcichra/lancachenet-ubuntu-nginx --push .
        cd ..
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push lancachenet/generic
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        git clone https://github.com/lancachenet/generic.git
        cd generic
        sed -i '1cFROM jrcichra/lancachenet-ubuntu-nginx' Dockerfile
        cat Dockerfile
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t jrcichra/lancachenet-generic --push .
        cd ..
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push lancachenet/monolithic
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        git clone https://github.com/lancachenet/monolithic.git
        cd monolithic
        sed -i '1cFROM jrcichra/lancachenet-generic' Dockerfile
        cat Dockerfile
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t jrcichra/lancachenet-monolithic --push .
        cd ..
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
