name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start it and try to change resolv.conf and check the IP that comes back
      run: |
        lsof -i :53
        docker-compose up -d
        echo -e "nameserver 127.0.0.1" > /etc/resolv.conf
        nslookup lancache.steamcontent.com
