name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start it and try to change resolv.conf and check the IP that comes back
      run: |
        sudo systemctl disable systemd-resolved.service
        sudo systemctl stop systemd-resolved
        sudo echo "[main]
        plugins=ifupdown,keyfile
        dns=default
        
        [ifupdown]
        managed=false
        
        [device]
        wifi.scan-rand-mac-address=no
        " > /etc/NetworkManager/NetworkManager.conf
        sudo service network-manager restart
        docker-compose up -d
        echo -e "nameserver 127.0.0.1" > /etc/resolv.conf
        nslookup lancache.steamcontent.com
